# main menu navigation
menu:
  Home: /
  Archive: /archives
  About: /about


widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter:
  facebook:
  linkedin:
  instagram:
  github: xuhaodong1

user:
  name: nihao
  avatar: /images/avatar.jpeg
  location: China HangZhou
  description: 不以功利为目的.
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: xuhaodong1/xuhaodong1.github.io # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/avatar.jpeg

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: /images/avatar.jpeg
